### PR TITLE
Add a method to determine the general turn direction of a path.

### PR DESCRIPTION
**Pull request by pentacular**
This will help in converting compound svg paths containing holes.

https://github.com/jscad/io/issues/71

### CODE REVIEW

**Comment by z3dev** [comment]
Just a few thoughts... the function is calculating the area of a closed path, so what not call it that getArea(). The IO library can do the simple checks for < > = 0

**Comment by pentacular** [comment]
Good idea.

**Comment by pentacular** [comment]
Oops -- I hit the wrong button.

I changed it to expose getArea() and found where the tests live. :)
Please take a look.

**Comment by kaosat-dev** [comment]
the tests are very desciptive, well done @pentacular  👍 
about the feature itself: 
- very useful to determin cw vs ccw 👍 
- but to be honest it feels a bit hackish to have negative areas 'mean' something, because there are no such things as negative areas in maths, so perhaps some other name would be better @z3dev :)
I honestly liked the previous name much better: it was very clear what it did :)

**Comment by kaosat-dev** [comment]
no worries @z3dev . I had to look it up just to be sure, but given our focus on clear, logical things for V2 we might want to avoid anything iffy ;)

**Comment by pentacular** [comment]
Ok, that should be up to date as getTurn -- let me know what you think.

**Comment by kaosat-dev** [comment]
@pentacular we are going to merge this one, thanks for the work ! :)
but a heads up : from today onwards we will not be accepting any PRs for the V1 version, as it means a lot more work for us to transfer the V1 changes to the very different V3

**Comment by pentacular** [comment]
Thanks.

Do you mean the V2 branch?
I'll see if it works with my codebase.

**Comment by kaosat-dev** [comment]
It won't haha the v2 branch is in very early stages. But we will incorporate your changes there don't worry :-)

**Pull request merged**
