### PR TITLE
refactor(csg.js): move Path2.innerToCAG to CAGFactories. Renamed as f…

### PR DESCRIPTION
**Pull request by jeromew**
This a pull request regarding innerToCAG => fromPath2

### CODE REVIEW

**Comment by z3dev** [comment]
@jeromew Big thanks for these changes.

Its great to have another set of eyes around this code. Exciting!

**Comment by jeromew** [comment]
@z3dev ok I will add the comments. I must admit I lazily followed the code style in Path2.js ;-)

**Comment by jeromew** [comment]
I added the documentation and squashed the commits. The doc makes it clear that getPoints returns the internal, potentially mutable points of the Path. I hesitated initially to return a copy of the points (cloning the path and returning the cloned points).

That would be slower since we add operations but I don't yet have a fine grained vision of what the state of things is in the library and it seems both of you prefer immutability.

tell me what you prefer and I will change the PR accordingly.

**Comment by z3dev** [comment]
The library follows the rule of returning a NEW object, but I guess there are probably some exceptions. Is there some simple rules for return values in JavaScript? I haven't seen anything, so I assume that returns are generally "references", unless there's a specific NEW.

In this case, returning the list of points is probably best.

**Comment by jeromew** [comment]
I saw many places indeed where returned objects are deep-cloned, creating a sort of immutability.
In javascript, basic types like string, booleans and integers are returned as they are. They are values and immutable in the sense that a value cannot be modified.

objects and arrays are returned as references. So modifying the elements modifies the original object. You need to deep-clone the object/array if you want something that can live its own life.

**Comment by z3dev** [comment]
Thanks for the contribution,

**Comment by kaosat-dev** [comment]
I know this one is merged , but thanks for the contribution :)
I am very much in favour of immutability as far as possible, but there are performance tradeoffs .
In general csg.js does seem to be on the side of returning new objects (I have been scolded by a contributor a few years back when I broke this rule :) 

This is again a subject worth more discussion, but there are ways to do rather fast object cloning with Object.assign & co these days , or the various functional programing libraries (I love Ramda), but  that works best with simpler data structures perhaps.

**Pull request merged**
