### PR TITLE
Initial Tests for Vector2D

### PR DESCRIPTION
**Pull request by z3dev**
Let's keep those tests rolling in!!!!

### CODE REVIEW

**Comment by kaosat-dev** [comment]
Great set of tests @z3dev !
Only one issue : failing Travis build due to a single rounding error:  is that test passing for you locally ?

**Comment by z3dev** [comment]
All test pass on Mac OS. I was wondering if there would be issues with rounding. We need another test for these values, something like "equal within 0.000001"

**Comment by kaosat-dev** [comment]
Since ava does not support other assertions (https://github.com/avajs/ava/issues/1094)

The simplest solution is this one 
```javascript
const precision = 0.000001
t.deepEqual(Math.abs(expected-observed) < precision) 
```
and voila ! solved :)
simple and straight to the point I think
if we really want to we could wrap it for re-use

```javascript
function almostEquals(t, observed, expected, precision=0.0000001){
t.deepEqual(Math.abs(expected-observed) < precision) 
}
```

and use it like this
```javascript
almostEquals(t, observed, expected)
```

**Comment by z3dev** [comment]
Looks like a function is required, which is explained here... http://floating-point-gui.de/errors/comparison/

I'll add a helper for this.

**Comment by z3dev** [comment]
@kaosat-dev please review the helper function. i tested the different cases of comparisons. Seems to work fine.

**Comment by kaosat-dev** [comment]
Yup , helper is ok, and all tests are passing, well done !

**Pull request merged**
