### PR TITLE
Fix/triangle()

### PR DESCRIPTION
**Pull request by lautr3k**
Just for fun and also because trigonometry is a bit boring for the end user.

jscad

```
  
            (B)
            / \
           /   \
      (c) /     \ (a)
         /       \
        /         \
    (A) _ _ _ _ _ _ (C)
            (b)
  
```

```javascript
function main(params) {
    // Defaults: Equilateral triangle with sides of 1
    let tri = triangle().scale(10);
    
    // AAS Triangles
    let AAS1 = triangle({ angles: { A: 45, B: 45 }, lengths: { a: 10 } });
    let AAS2 = triangle({ angles: { A: 45, B: 45 }, lengths: { b: 10 } });
    let AAS3 = triangle({ angles: { B: 45, C: 90 }, lengths: { b: 10 } });
    let AAS4 = triangle({ angles: { B: 45, C: 90 }, lengths: { c: 14.142135623730951 } });
    let AAS5 = triangle({ angles: { C: 90, A: 45 }, lengths: { c: 14.142135623730951 } });
    let AAS6 = triangle({ angles: { C: 90, A: 45 }, lengths: { a: 10 } });
    
    // ASA Triangles
    let ASA1 = triangle({ angles: { A: 45, B: 45 }, lengths: { c: 14.142135623730951 } });
    let ASA2 = triangle({ angles: { B: 45, C: 90 }, lengths: { a: 10 } });
    let ASA3 = triangle({ angles: { C: 90, A: 45 }, lengths: { b: 10 } });
    
    // SAS Triangles
    let SAS1 = triangle({ angles: { A: 45 }, lengths: { b: 10, c: 14.142135623730951 } });
    let SAS2 = triangle({ angles: { B: 45 }, lengths: { a: 10, c: 14.142135623730951 } });
    let SAS3 = triangle({ angles: { C: 90 }, lengths: { a: 10, b: 10 } });
    
    // SSA Triangles
    let SSA1 = triangle({ angles: { A: 45 }, lengths: { a: 10, b: 10 } });
    let SSA2 = triangle({ angles: { B: 45 }, lengths: { a: 10, b: 10 } });
    let SSA3 = triangle({ angles: { B: 45 }, lengths: { b: 10, c: 14.142135623730951 } });
    let SSA4 = triangle({ angles: { C: 90 }, lengths: { b: 10, c: 14.142135623730951 } });
    let SSA5 = triangle({ angles: { C: 90 }, lengths: { a: 10, c: 14.142135623730951 } });
    let SSA6 = triangle({ angles: { A: 45 }, lengths: { a: 10, c: 14.142135623730951 } });
    
    // SSA Two solutions
    let SSA7 = triangle({ angles: { A: 31 }, lengths: { a: 8, c: 13 }, returnBiggest: true });
    let SSA8 = triangle({ angles: { A: 31 }, lengths: { a: 8, c: 13 }, returnBiggest: false });
    
    // SSS Triangles
    let SSS1 = triangle({ lengths: { a: 10, b: 10, c: 14.142135623730951 } });
    
    return [
        tri,
        
        AAS1.translate([0,  -15, 0]),
        AAS2.translate([15, -15, 0]),
        AAS3.translate([30, -15, 0]),
        AAS4.translate([45, -15, 0]),
        AAS5.translate([60, -15, 0]),
        AAS6.translate([75, -15, 0]),
        
        ASA1.translate([0,  -30, 0]),
        ASA2.translate([15, -30, 0]),
        ASA3.translate([30, -30, 0]),
        
        SAS1.translate([0,  -45, 0]),
        SAS2.translate([15, -45, 0]),
        SAS3.translate([30, -45, 0]),
        
        SSA1.translate([0,  -60, 0]),
        SSA2.translate([15, -60, 0]),
        SSA3.translate([30, -60, 0]),
        SSA4.translate([45, -60, 0]),
        SSA5.translate([60, -60, 0]),
        SSA6.translate([75, -60, 0]),
        
        SSA7.translate([0,  -75, 0]),
        SSA8.translate([15, -75, 0]),
        
        SSS1.translate([0, -90, 0])
    ];
}
```

### CODE REVIEW

**Comment by z3dev** [comment]
Once again... BIG THANKS!

I have one suggestion as we have beed debating the organization of the library. I think we should have separate source files for each of the primitives, operations, etc.

**Comment by z3dev** [comment]
By the way, another shape that is on my list of things to do is STARS.

https://github.com/mikolalysenko/star-polygon

**Comment by lautr3k** [comment]
As discussed with @kaosat-dev , I understand that this is removed in v2 and it's fine like that. I did it for fun and will be used in an external library, like your STARS function.

**Comment by z3dev** [comment]
I thought the V2 API was still undecided. I don't expect just circles and squares. ;)

**Comment by z3dev** [comment]
@kaosat-dev well, actually everything can be created from polygon(), so what's the point of the API?

CONVIENCE and EASE OF USE

We are trying to develop an API that can be easily used by folks with very little math / geometry knowledge. So, let's make it easy.

The same goes for rectangle versus square, or circle versus ellipse, rotate versus rotateZ, etc. All of these are for ease of use.

I do agree that we need a central core of functionality, but the API for users can very rich and easy. Maybe even several API libraries.

**Comment by kaosat-dev** [comment]
several API libraries => IE not core!
what is the benefit of triangle ? who creates triangles ? it was not even working before ! so no useage :)
some aliases can be useful for convenience, but let's try to keep it minimal.
We could add every possible geometry , but that would make it non trivial to maintain, and 99% would end up never being use.
Minimalism is a feature !

**Comment by z3dev** [comment]
@lautr3k Be sure to save that code. I don't think this discussion has finished yet.

Once @kaosat-dev has a first cut at the API, then the fun begins to provide something useful.

**Pull request closed without merging**
