### PR TITLE
refactor(csg.js): split out various pieces into seperate modules

### PR DESCRIPTION
**Pull request by kaosat-dev**
This pr splits up the HUGE csg.js file into more manageable , specialised chunks
- split out various 2d & 3d shapes
- split out maths (vectors, matrices etc)
- split out utilities
- make code base more manageable and offer better overview for future improvements

This might take a while because of the huge amount of interdependencies, but it is feasible :) (I have [done it before in Coffeescript](https://github.com/kaosat-dev/CoffeeSCad/tree/dev/src/app/core/projects/csg)

### CODE REVIEW

**Comment by z3dev** [comment]
It seems to me that some "classes" are redundant. For example CSG.Line2D and CAG.Path. Good luck.

**Comment by z3dev** [comment]
Wow! That's a huge improvement in readability and understandability.

Look fine.

**Comment by kaosat-dev** [comment]
thanks @z3dev !

**Comment by kaosat-dev** [comment]
Not perfect, but it all works ok, I plan a second one to improve things, but one step at a time, merging!

**Pull request merged**
